server:
  port: 8888
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
        defaultZone: http://localhost:${server.port}/eureka/
  instance:
    statusPageUrl: https://${eureka.hostname}/info
    healthCheckUrl: https://${eureka.hostname}/health
    homePageUrl: https://${eureka.hostname}/
